config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  match "/404", to: "errors#not_found", via: :all

  resources :jobs, except: [:show] do
    resources :application_forms
  end
  root to: "jobs#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable
end

app/models/application_form.rb
class ApplicationForm < ActiveRecord::Base
  belongs_to :job

  validates_presence_of :name, :email, :address, :phone_number, :job_id
  validates_uniqueness_of :email, :phone_number, scope: :job_id
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :application_forms, dependent: :delete_all

  validates_presence_of :name, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :show]
  before_action :set_job, only: [:index, :new, :create]
  before_action :set_application_form, only: [:show]

  # GET /application_forms
  def index
    @application_forms = @job.application_forms
  end

  # GET /application_forms/1
  def show
  end

  # GET /application_forms/new
  def new
    @application_form = @job.application_forms.build
  end

  # POST /application_forms
  def create
    @application_form = @job.application_forms.build(application_form_params)

    if @application_form.save
      redirect_to jobs_url, notice: 'Application successfully submitted'
    else
      render :new
    end
  end

  private
    def set_job
      @job = Job.find(params[:job_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_application_form
      @application_form = ApplicationForm.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def application_form_params
      params.require(:application_form).permit(:name, :email, :address, :phone_number, :job_id)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render status: :not_found
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :update, :destroy, :new]
  before_action :set_job, only: [:edit, :update, :destroy]

  # GET /jobs
  def index
    @jobs = Job.all
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_url, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /jobs/1
  def update
    if @job.update(job_params)
      redirect_to jobs_url, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /jobs/1
  def destroy
    @job.destroy
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def job_params
      params.require(:job).permit(:name, :description)
    end
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/_sidebar.html.erb
<div class="mdl-layout__drawer">
  <header class="drawer-header">
    <span class="mdl-layout-title"><%= current_admin.email %></span>
  </header>
  <nav class="mdl-navigation">
    <%= link_to "New Job", new_job_path, class: "mdl-navigation__link" %>
    <%= link_to "Sign Out", destroy_admin_session_path, class: "mdl-navigation__link", method: :delete %>
  </nav>
</div>

app/views/application_forms/_form.html.erb
<%= form_for [@job, @application_form] do |f| %>
  <% if @application_form.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@application_form.errors.count, "error") %> prohibited this application_form from being saved:
      </h2>

      <ul>
      <% @application_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mdl-textfield mdl-js-textfield">
    <%= f.label :name, class: "mdl-textfield__label" %>
    <%= f.text_field :name, class: "mdl-textfield__input" %>
  </div>
  <br>
  <div class="field mdl-textfield mdl-js-textfield">
    <%= f.label :email, class: "mdl-textfield__label" %>
    <%= f.text_field :email, class: "mdl-textfield__input" %>
  </div>
  <br>
  <div class="field mdl-textfield mdl-js-textfield">
    <%= f.label :address, class: "mdl-textfield__label" %>
    <%= f.text_field :address, class: "mdl-textfield__input" %>
  </div>
  <br>
  <div class="field mdl-textfield mdl-js-textfield">
    <%= f.label :phone_number, class: "mdl-textfield__label" %>
    <%= f.text_field :phone_number, class: "mdl-textfield__input" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit",  class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    <%= link_to 'Back', jobs_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" %>
  </div>
<% end %>

app/views/application_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Applications for <%= @job.name %></h2>

<table class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Name</th>
      <th class="mdl-data-table__cell--non-numeric">Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application_forms.each do |application_form| %>
      <tr>
        <td class="mdl-data-table__cell--non-numeric"><%= application_form.name %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= application_form.email %></td>
        <td><%= link_to 'Show', job_application_form_path(application_form.job, application_form) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/application_forms/new.html.erb
<h2>Applying for <%= @job.name %></h2>

<%= render 'form' %>

app/views/application_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application_form.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @application_form.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @application_form.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @application_form.phone_number %>
</p>

<%= link_to 'Back', job_application_forms_path(@application_form.job) %>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mdl-textfield mdl-js-textfield">
    <%= f.label :name, class: "mdl-textfield__label" %>
    <%= f.text_field :name, class: "mdl-textfield__input" %>
  </div>
  <br>
  <div class="field mdl-textfield mdl-js-textfield">
    <%= f.label :description, class: "mdl-textfield__label" %>
    <%= f.text_area :description, class: "mdl-textfield__input" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    <%= link_to 'Back', jobs_path, class: "mdl-button mdl-js-button mdl-button--raised" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<h3>Jobs Listing</h3>

<% if @jobs.blank? %>
  <h3><small>No job listings available</small></h3>
<% end %>

<% @jobs.each do |job| %>
  <div class="mdl-card mdl-shadow--2dp mdl-cell--12-col">
    <div class="mdl-card__title mdl-card--expand">
      <h2 class="mdl-card__title-text"><%= job.name %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <%= job.description %>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= link_to_if !admin_signed_in?, "Apply", new_job_application_form_path(job), class: "mdl-button--colored mdl-button mdl-js-button mdl-js-ripple-effect" do %>
        <%= link_to "Applications", job_application_forms_path(job), class: "mdl-button--colored mdl-button mdl-js-button" %>
        <%= link_to "Edit", edit_job_path(job), class: "mdl-button--colored mdl-button mdl-js-button" %>
        <%= link_to "Delete", job_path(job), method: :delete, data: {confirm: "Are you sure?"}, class: "mdl-button--colored mdl-button mdl-js-button" %>
      <% end %>
    </div>
  </div>
  <div class="job-separator mdl-cell--1-col"></div>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carreerology</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.3/material.blue-light_blue.min.css" />
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.3/material.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout <%=  admin_signed_in? ? "mdl-layout--fixed-drawer mdl-layout--fixed-header" : "" %>" >
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Carreerology</span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation">
            <%= link_to "Home", root_path, class: "mdl-navigation__link" %>
            <% unless admin_signed_in? %>
              <%= link_to "Sign In", new_admin_session_path, class: "mdl-navigation__link" %>
            <% end %>
          </nav>
        </div>
      </header>
      <% if admin_signed_in? %>
        <%= render "admin/sidebar" %>
      <% end %>

      <main class="mdl-layout__content">
        <div class="mdl-grid page-content">
          <div class="mdl-cell mdl-cell--12-col">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %> </p>

            <%= yield %>
          </div>
        </div>
      </main>
    </div>
</body>
</html>